# faster builds on new travis setup not using sudo
sudo: false

language: php

php:
  - 7.1
  - 7.2

branches:
  only: master

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - |
    # php.ini configuration
    INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    echo date.timezone = Europe/Madrid >> $INI
    echo memory_limit = -1 >> $INI
    echo session.gc_probability = 0 >> $INI
    echo opcache.enable_cli = 1 >> $INI
    echo apc.enable_cli = 1 >> $INI
    echo extension = redis.so >> $INI
    echo extension = memcached.so >> $INI
    echo extension = mongodb.so >> $INI

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer install --no-interaction --prefer-dist

after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - composer validate --no-check-lock
  - vendor/bin/phpunit

services:
  - mongodb
  - memcached
  - redis-server
