# faster builds on new travis setup not using sudo
sudo: false

language: php

php:
  - 7.0
  - 7.1

branches:
  only: master

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - |
    if [[ $TRAVIS_PHP_VERSION != '7.1' && $TRAVIS_PHP_VERSION != hhv* ]]; then
        # disable xdebug for performance reasons when code coverage is not needed
        # note: xdebug on hhvm is disabled by default
        phpenv config-rm xdebug.ini || echo "xdebug is not installed"
    fi
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_script:
  # enable code coverage on PHP 7.1, only one PHP version needs to generate coverage data
  - |
    if [ $TRAVIS_PHP_VERSION = '7.1' ]; then
      CODECEPTION_FLAGS="--coverage-xml"
    fi

script:
  - composer validate --no-check-lock
  - vendor/bin/codecept run $CODECEPTION_FLAGS

services:
  - mongodb
  - memcached
  - redis-server
