<?php

declare(strict_types=1);

/*
 * This file is part of the univeros/framework
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

namespace Altair\AgentSpec\Generator;

use Altair\AgentSpec\Model\PackageDescriptor;

/**
 * Renders the global `.agent/MANIFEST.md` index — one line per package with
 * a link to its detailed manifest. Output is deterministic.
 */
class IndexGenerator
{
    public const string HEADER = '# Altair Framework — Agent Manifest Index';

    /**
     * @param list<PackageDescriptor> $packages Pre-sorted by package name.
     */
    public function render(array $packages, string $packagesDirectory = 'packages'): string
    {
        $body = [
            self::HEADER,
            '',
            'Machine-readable descriptions of every framework sub-package, generated by `univeros/agent-spec`.',
            '',
            '| Package | Namespace | Description |',
            '|---|---|---|',
        ];

        foreach ($packages as $package) {
            $link = \sprintf('[%s](%s/%s.md)', $package->packageName, $packagesDirectory, $package->manifestSlug);
            $body[] = \sprintf(
                '| %s | `%s` | %s |',
                $link,
                $package->rootNamespace,
                $this->escapeTable($package->description),
            );
        }

        return implode("\n", $body) . "\n";
    }

    private function escapeTable(string $value): string
    {
        return str_replace('|', '\\|', $value);
    }
}
