endpoint:
  method: GET
  path: /store/inventory
  summary: 'Returns pet inventories by status.'
  tags:
    - inventory
output:
  200:
    body: {  }
domain:
  class: App\Inventory\GetInventory
  invocation: __invoke
