<?php

declare(strict_types=1);

/*
 * This file is part of the univeros/framework
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

namespace Altair\Scaffold\Sdk\TypeScript;

use Altair\Scaffold\Sdk\Contracts\EmitterInterface;
use Altair\Scaffold\Sdk\EmittedSdk;
use Altair\Scaffold\Sdk\Model\OpenApiDocument;
use Altair\Scaffold\Sdk\Model\OperationModel;
use Altair\Scaffold\Sdk\Model\SchemaType;
use Override;

/**
 * Emits a `fetch`-based, zero-runtime-dependency TypeScript SDK.
 *
 * - `interface` for object shapes, `type` for unions/enums
 * - each operation a separately-exported tree-shakeable function
 * - response modelled as a status-discriminated union
 *   (`{ status: 201; data: ... } | { status: 422; data: ... }`)
 * - an `ApiOptions` type, an `ApiError` class, a private `request()` helper
 *
 * Output is deterministic (named types alpha-sorted, operations in
 * document order) so `--check` can diff it for CI drift.
 */
final readonly class TypeScriptEmitter implements EmitterInterface
{
    #[Override]
    public function language(): string
    {
        return 'typescript';
    }

    #[Override]
    public function defaultFileName(): string
    {
        return 'sdk.ts';
    }

    #[Override]
    public function emit(OpenApiDocument $document, bool $multiFile = false): EmittedSdk
    {
        $types = $this->renderNamedTypes($document);
        $operations = $this->renderOperations($document);

        if ($multiFile) {
            return new EmittedSdk([
                'types.ts' => $this->header() . $types . "\n",
                'client.ts' => $this->header() . "import type * as Types from './types';\n\n" . $this->runtime() . $operations,
            ]);
        }

        $body = $this->header()
            . $this->runtime()
            . ($types === '' ? '' : $types . "\n")
            . $operations;

        return new EmittedSdk([$this->defaultFileName() => rtrim($body) . "\n"]);
    }

    private function header(): string
    {
        return "// generated by univeros/scaffold — do not edit by hand.\n"
            . "/* eslint-disable */\n\n";
    }

    private function runtime(): string
    {
        return <<<'TS'
            export interface ApiOptions {
              baseUrl?: string;
              headers?: Record<string, string>;
              signal?: AbortSignal;
              fetch?: typeof fetch;
            }

            export class ApiError extends Error {
              constructor(
                public readonly status: number,
                public readonly body: unknown,
              ) {
                super(`API request failed with status ${status}`);
                this.name = 'ApiError';
              }
            }

            async function request(
              method: string,
              path: string,
              options: ApiOptions & { body?: unknown } = {},
            ): Promise<{ status: number; data: unknown }> {
              const { baseUrl = '', headers = {}, signal, fetch: fetchImpl = fetch, body } = options;
              const response = await fetchImpl(`${baseUrl}${path}`, {
                method,
                headers: { 'content-type': 'application/json', ...headers },
                body: body === undefined ? undefined : JSON.stringify(body),
                signal,
              });
              const text = await response.text();
              const data = text === '' ? null : JSON.parse(text);
              return { status: response.status, data };
            }


            TS;
    }

    private function renderNamedTypes(OpenApiDocument $document): string
    {
        $names = array_keys($document->namedSchemas);
        sort($names);

        $out = '';
        foreach ($names as $name) {
            $out .= $this->renderNamedType($name, $document->namedSchemas[$name]) . "\n";
        }

        return $out;
    }

    private function renderNamedType(string $name, SchemaType $schema): string
    {
        if ($schema->kind === SchemaType::ENUM) {
            return \sprintf("export type %s = %s;\n", $name, $this->enumUnion($schema));
        }

        if ($schema->isObject()) {
            return \sprintf("export interface %s {\n%s}\n", $name, $this->objectBody($schema));
        }

        return \sprintf("export type %s = %s;\n", $name, $this->typeExpr($schema));
    }

    private function renderOperations(OpenApiDocument $document): string
    {
        $out = '';
        foreach ($document->operations as $operation) {
            $out .= $this->renderOperation($operation);
        }

        return $out;
    }

    private function renderOperation(OperationModel $operation): string
    {
        $fn = $operation->operationId;
        $responseType = ucfirst($fn) . 'Response';

        $out = $this->renderResponseUnion($responseType, $operation) . "\n";

        $params = [];
        foreach ($operation->pathParameters as $param) {
            $params[] = $this->camel($param) . ': string';
        }

        $requestBody = $operation->requestBody;
        if ($requestBody instanceof SchemaType) {
            $params[] = 'body: ' . $this->typeExpr($requestBody);
        }

        $params[] = 'options: ApiOptions = {}';

        $pathExpr = $this->pathExpression($operation);
        $requestArgs = $requestBody instanceof SchemaType ? 'body, ...options' : '...options';

        $summary = $operation->summary !== '' ? '/** ' . $operation->summary . " */\n" : '';

        return $out . \sprintf(
            "%sexport async function %s(%s): Promise<%s> {\n  return request('%s', %s, { %s }) as Promise<%s>;\n}\n\n",
            $summary,
            $fn,
            implode(', ', $params),
            $responseType,
            $operation->method,
            $pathExpr,
            $requestArgs,
            $responseType,
        );
    }

    private function renderResponseUnion(string $typeName, OperationModel $operation): string
    {
        if ($operation->responses === []) {
            return \sprintf("export type %s = { status: number; data: unknown };\n", $typeName);
        }

        $members = [];
        foreach ($operation->responses as $response) {
            $statusToken = $response->statusIsNumeric() ? $response->status : 'number';
            $dataType = $response->schema === null ? 'null' : $this->typeExpr($response->schema);
            $members[] = \sprintf('  | { status: %s; data: %s }', $statusToken, $dataType);
        }

        return \sprintf("export type %s =\n%s;\n", $typeName, implode("\n", $members));
    }

    private function pathExpression(OperationModel $operation): string
    {
        if ($operation->pathParameters === []) {
            return "'" . $operation->path . "'";
        }

        $template = $operation->path;
        foreach ($operation->pathParameters as $param) {
            $template = str_replace('{' . $param . '}', '${' . $this->camel($param) . '}', $template);
        }

        return '`' . $template . '`';
    }

    private function objectBody(SchemaType $schema): string
    {
        $out = '';
        foreach ($schema->properties as $name => $property) {
            $optional = $property['required'] ? '' : '?';
            $out .= \sprintf("  %s%s: %s;\n", $this->propertyName($name), $optional, $this->typeExpr($property['schema']));
        }

        return $out;
    }

    private function typeExpr(SchemaType $schema): string
    {
        $base = match ($schema->kind) {
            SchemaType::REF => (string) $schema->ref,
            SchemaType::ARRAY => $this->arrayExpr($schema),
            SchemaType::ENUM => $this->enumUnion($schema),
            SchemaType::OBJECT => $this->inlineObject($schema),
            SchemaType::SCALAR => $this->scalarExpr($schema),
            default => 'unknown',
        };

        return $schema->nullable ? $base . ' | null' : $base;
    }

    private function arrayExpr(SchemaType $schema): string
    {
        $items = $schema->items ?? SchemaType::mixed();
        $inner = $this->typeExpr($items);

        // Wrap unions so `(A | null)[]` reads correctly.
        return str_contains($inner, ' ') ? '(' . $inner . ')[]' : $inner . '[]';
    }

    private function inlineObject(SchemaType $schema): string
    {
        if ($schema->properties === []) {
            return 'Record<string, unknown>';
        }

        $parts = [];
        foreach ($schema->properties as $name => $property) {
            $optional = $property['required'] ? '' : '?';
            $parts[] = \sprintf('%s%s: %s', $this->propertyName($name), $optional, $this->typeExpr($property['schema']));
        }

        return '{ ' . implode('; ', $parts) . ' }';
    }

    private function enumUnion(SchemaType $schema): string
    {
        if ($schema->enumValues === []) {
            return 'string';
        }

        return implode(' | ', array_map(static fn(string $v): string => "'" . $v . "'", $schema->enumValues));
    }

    private function scalarExpr(SchemaType $schema): string
    {
        return match ($schema->scalarType) {
            'integer', 'number' => 'number',
            'boolean' => 'boolean',
            default => 'string',
        };
    }

    private function propertyName(string $name): string
    {
        return preg_match('/^[A-Za-z_$][A-Za-z0-9_$]*$/', $name) === 1 ? $name : "'" . $name . "'";
    }

    private function camel(string $value): string
    {
        $value = (string) preg_replace('/[^A-Za-z0-9]+/', ' ', $value);

        return lcfirst(str_replace(' ', '', ucwords($value)));
    }
}
