<?php

declare(strict_types=1);

/*
 * This file is part of the univeros/framework
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

namespace Altair\Scaffold\Sdk\Python;

use Altair\Scaffold\Sdk\Contracts\EmitterInterface;
use Altair\Scaffold\Sdk\EmittedSdk;
use Altair\Scaffold\Sdk\Model\OpenApiDocument;
use Altair\Scaffold\Sdk\Model\OperationModel;
use Altair\Scaffold\Sdk\Model\SchemaType;
use Override;

/**
 * Emits an `httpx` + `pydantic v2` Python SDK with both sync and async
 * client classes.
 *
 * - `pydantic.BaseModel` per object schema (free runtime validation)
 * - `str, Enum` classes for enums
 * - snake_case fields with `Field(alias=...)` when the wire name differs
 * - `Client` (sync) + `AsyncClient` (async) — httpx supports both
 * - type hints throughout; targets `mypy --strict`
 *
 * Deterministic output (models alpha-sorted, methods in document order).
 */
final readonly class PythonEmitter implements EmitterInterface
{
    #[Override]
    public function language(): string
    {
        return 'python';
    }

    #[Override]
    public function defaultFileName(): string
    {
        return 'client.py';
    }

    #[Override]
    public function emit(OpenApiDocument $document, bool $multiFile = false): EmittedSdk
    {
        $models = $this->renderModels($document);
        $sync = $this->renderClient($document, async: false);
        $async = $this->renderClient($document, async: true);

        if ($multiFile) {
            return new EmittedSdk([
                'models.py' => $this->header() . $this->modelImports() . $models,
                'client.py' => $this->header() . $this->clientImports() . "from .models import *  # noqa: F403\n\n\n" . $sync . "\n\n" . $async,
            ]);
        }

        $body = $this->header()
            . $this->fullImports()
            . $models
            . "\n"
            . $sync
            . "\n\n"
            . $async;

        return new EmittedSdk([$this->defaultFileName() => rtrim($body) . "\n"]);
    }

    private function header(): string
    {
        return "# generated by univeros/scaffold — do not edit by hand.\n# ruff: noqa\n\n";
    }

    private function fullImports(): string
    {
        return "from __future__ import annotations\n\n"
            . "from enum import Enum\n"
            . "from typing import Any\n\n"
            . "import httpx\n"
            . "from pydantic import BaseModel, Field\n\n\n";
    }

    private function modelImports(): string
    {
        return "from __future__ import annotations\n\n"
            . "from enum import Enum\n"
            . "from typing import Any\n\n"
            . "from pydantic import BaseModel, Field\n\n\n";
    }

    private function clientImports(): string
    {
        return "from __future__ import annotations\n\n"
            . "from typing import Any\n\n"
            . "import httpx\n\n";
    }

    private function renderModels(OpenApiDocument $document): string
    {
        $names = array_keys($document->namedSchemas);
        sort($names);

        $out = '';
        foreach ($names as $name) {
            $schema = $document->namedSchemas[$name];
            if ($schema->kind === SchemaType::ENUM) {
                $out .= $this->renderEnum($name, $schema) . "\n\n";
            } elseif ($schema->isObject()) {
                $out .= $this->renderModel($name, $schema) . "\n\n";
            }
        }

        return $out;
    }

    private function renderEnum(string $name, SchemaType $schema): string
    {
        $out = \sprintf("class %s(str, Enum):\n", $name);
        if ($schema->enumValues === []) {
            return $out . "    pass\n";
        }

        foreach ($schema->enumValues as $value) {
            $out .= \sprintf("    %s = %s\n", $this->constName($value), $this->pyString($value));
        }

        return $out;
    }

    private function renderModel(string $name, SchemaType $schema): string
    {
        $out = \sprintf("class %s(BaseModel):\n", $name);
        if ($schema->properties === []) {
            return $out . "    pass\n";
        }

        foreach ($schema->properties as $wireName => $property) {
            $fieldName = $this->snake($wireName);
            $type = $this->typeHint($property['schema']);
            $optional = !$property['required'];

            if ($optional) {
                $type .= ' | None';
            }

            $default = $this->fieldDefault($wireName, $fieldName, $optional);
            $out .= \sprintf("    %s: %s%s\n", $fieldName, $type, $default);
        }

        return $out;
    }

    private function fieldDefault(string $wireName, string $fieldName, bool $optional): string
    {
        $needsAlias = $wireName !== $fieldName;

        if ($needsAlias && $optional) {
            return \sprintf(' = Field(default=None, alias=%s)', $this->pyString($wireName));
        }

        if ($needsAlias) {
            return \sprintf(' = Field(alias=%s)', $this->pyString($wireName));
        }

        if ($optional) {
            return ' = None';
        }

        return '';
    }

    private function renderClient(OpenApiDocument $document, bool $async): string
    {
        $className = $async ? 'AsyncClient' : 'Client';
        $httpxClient = $async ? 'httpx.AsyncClient' : 'httpx.Client';

        $out = \sprintf("class %s:\n", $className);
        $out .= \sprintf("    def __init__(self, base_url: str, client: %s | None = None) -> None:\n", $httpxClient);
        $out .= \sprintf("        self._client = client or %s(base_url=base_url)\n\n", $httpxClient);

        foreach ($document->operations as $operation) {
            $out .= $this->renderMethod($operation, $async);
        }

        return rtrim($out, "\n") . "\n";
    }

    private function renderMethod(OperationModel $operation, bool $async): string
    {
        $name = $this->snake($operation->operationId);
        $params = ['self'];
        foreach ($operation->pathParameters as $param) {
            $params[] = $this->snake($param) . ': str';
        }

        $requestBody = $operation->requestBody;
        if ($requestBody instanceof SchemaType) {
            $params[] = 'body: ' . $this->typeHint($requestBody);
        }

        $returnType = $this->returnType($operation);
        $def = $async ? 'async def' : 'def';
        $await = $async ? 'await ' : '';

        $pathExpr = $this->pathExpression($operation);
        $bodyArg = $requestBody instanceof SchemaType
            ? ', json=body.model_dump(by_alias=True, exclude_none=True) if hasattr(body, "model_dump") else body'
            : '';

        $out = \sprintf("    %s %s(%s) -> %s:\n", $def, $name, implode(', ', $params), $returnType);
        if ($operation->summary !== '') {
            $out .= \sprintf("        \"\"\"%s\"\"\"\n", $operation->summary);
        }

        $out .= \sprintf("        response = %sself._client.request(%s, %s%s)\n", $await, $this->pyString($operation->method), $pathExpr, $bodyArg);
        $out .= "        response.raise_for_status()\n";

        return $out . "        return response.json()\n\n";
    }

    private function returnType(OperationModel $operation): string
    {
        $successSchemas = [];
        foreach ($operation->successResponses() as $response) {
            if ($response->schema !== null) {
                $successSchemas[$this->typeHint($response->schema)] = true;
            }
        }

        $types = array_keys($successSchemas);

        return match (\count($types)) {
            0 => 'Any',
            1 => $types[0],
            default => implode(' | ', $types),
        };
    }

    private function pathExpression(OperationModel $operation): string
    {
        if ($operation->pathParameters === []) {
            return $this->pyString($operation->path);
        }

        $template = $operation->path;
        foreach ($operation->pathParameters as $param) {
            $template = str_replace('{' . $param . '}', '{' . $this->snake($param) . '}', $template);
        }

        return 'f' . $this->pyString($template);
    }

    private function typeHint(SchemaType $schema): string
    {
        $base = match ($schema->kind) {
            SchemaType::REF => (string) $schema->ref,
            SchemaType::ARRAY => 'list[' . $this->typeHint($schema->items ?? SchemaType::mixed()) . ']',
            SchemaType::ENUM => $schema->enumValues === [] ? 'str' : 'str',
            SchemaType::OBJECT => 'dict[str, Any]',
            SchemaType::SCALAR => $this->scalarHint($schema),
            default => 'Any',
        };

        return $schema->nullable ? $base . ' | None' : $base;
    }

    private function scalarHint(SchemaType $schema): string
    {
        return match ($schema->scalarType) {
            'integer' => 'int',
            'number' => 'float',
            'boolean' => 'bool',
            default => $schema->format === 'date-time' ? 'str' : 'str',
        };
    }

    private function snake(string $value): string
    {
        $value = (string) preg_replace('/[^A-Za-z0-9]+/', '_', $value);
        $value = (string) preg_replace('/([a-z0-9])([A-Z])/', '$1_$2', $value);

        return strtolower(trim($value, '_'));
    }

    private function constName(string $value): string
    {
        $name = strtoupper($this->snake($value));

        return preg_match('/^[A-Z]/', $name) === 1 ? $name : 'V_' . $name;
    }

    private function pyString(string $value): string
    {
        return '"' . str_replace(['\\', '"'], ['\\\\', '\\"'], $value) . '"';
    }
}
